# Default values for mulesoft-runtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

maven:
  groupId: 
  artifactId:
  artifactVersion:

java:
  additionalParam:

filebeat:
  name: filebeat

proxy:
  host:
  port:

replicaCount: 1

image:
  repository: WeEuS01PrdAcrAksc.azurecr.io/mulesoft-runtime
  pullPolicy: IfNotPresent

# imagePullSecrets: 
#   - name: docker-registry-secret

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: host.ah.nl
      paths: [ /ah/domain/service/v2 ]
  tls: 
    - secretName: tls-cert
      hosts:
        - host.ah.nl

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 0.1
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

dynatrace:
  enabled: false
  environment: acc
  acc:
    url: https://dynatrace.digitaldev.nl/e/a20c02ac-d4ea-4e72-80ea-f7270e8fe19c/api/
    token: T1of2_m0QTWva6V3g-Suu
  prd:
    url: https://dynatrace.digitaldev.nl/e/f51771da-652e-43ff-a066-fab0e1ce541b/api/
    token: gM0X1CSATKi44ps3pclRq 

nodeSelector: {}

tolerations: []

affinity: {}
